const getRandomNumber = (min, max) => {
  return Math.random() * (max - min) + min;
};

const getPrice = () => {
  const price = getRandomNumber(0, 2_000);

  if (price < 400) {
    return "Gratuito";
  }

  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(price);
};

export const events = Object.freeze([
  {
    id: 1,
    title: "Preludio circular",
    description: [
      "En esta exposición, el artista nos presenta 22 obras realizadas en Lienzografías sobre canvas en aluminio en formato circular, mostrando la feminidad de la naturaleza que junto a lo sensual constituyen sus ejes temáticos.",
    ],
    image: "/images/event1.jpg",
    dates: "11 may de 2022 - 11 jul de 2022",
    entree: getPrice(),
    location: "Plaza de la Cultura Juan Pablo Duarte",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Museo de Arte Moderno de Santo Domingo - MAM"],
    artists: ["Ángel Ricardo Rivera"],
    artworks: [
      "/images/event1-1.jpg",
      "/images/event1-2.jpg",
      "/images/event1-3.jpg",
      "/images/event1-4.jpg",
      "/images/event1-5.jpg",
      "/images/event1-6.webp",
      "/images/event1-7.webp",
      "/images/event1-8.webp",
      "/images/event1-9.webp",
    ],
  },
  {
    id: 2,
    title: "Tierra de Nadie",
    description: [
      "La galería Lyle O. Reitzel Arte Contemporáneo celebra sus 27 años de existencia, presentando una espectacular exposición individual a cargo del artista dominicano Gerard Ellis, titulada “Tierra De Nadie”.",
    ],
    image: "/images/event2.jpg",
    dates: "05 may de 2022 - 30 jun de 2022",
    entree: getPrice(),
    location: "Gustavo Mejia Ricart, Esq. Av. Abraham Lincoln",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Lyle O. Reitzel Gallery"],
    artists: ["Gerard Ellis"],
    artworks: [],
  },
  {
    id: 3,
    title: "DIALOGOS ANALOGICOS",
    description: [
      "Esta exposición es una invitación a conocer las inquietudes de un grupo de mujeres que comparten el amor por la fotografía analógica y que buscan comunicar, mediante un discurso visual cargado de verdad y belleza, lo que significa ser mujer en el mundo.",
    ],
    image: "/images/event3.png",
    dates: "04 mar de 2022 - 16 abr de 2022",
    entree: getPrice(),
    location: "Centro Cultural de España",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Centro Cultural de España - CCE Santo Domingo"],
    artists: ["Liú Marino"],
    artworks: [],
  },
  {
    id: 4,
    title: "En busca de lo imposible",
    description: ["Seis artistas hiperrealistas en un solo espacio."],
    image: "/images/event4.jpg",
    dates: "Desde 16 feb de 2022",
    entree: getPrice(),
    location: "Galería ASR Contemporáneo",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Galería ASR Contemporáneo"],
    artists: [
      "Domingo Rosario",
      "Francisco Collado",
      "Karina Rodríguez",
      "Pamela Rivera",
      "Ruddy Taveras",
      "Windel Gonzalez",
    ],
    artworks: [],
  },
  {
    id: 5,
    title: "Imágenes de Carnaval: Centro, Sur y Línea Nordeste",
    description: [
      "¿De dónde vienen estas olas?",
      "Pedro Farías-Nardi es una de las personalidades artísticas más reflexivas y definidas en el mundo de la creación fotográfica dominicana. Posee una sólida formación como antropólogo social. De igual forma, una extensa preparación en el quehacer fotográfico en prestigiosas instituciones internacionales. Entre sus principales maestros del lente podemos citar a Susan Meiselas, Antonin Kratochvil, Davild Alan Harvey, Larry Fink y Bob Aldeman para solo mencionar a algunos. Docente universitario, con una vasta cultura, desarrollada en más de tres décadas, lo convierten en un antropólogo visual de primer orden en nuestro país.",
      "Su forma de acercarse a sus retratados, con un prodigioso manejo de un lente fijo y un encuadre muy particular, lo hacen poseedor de un estilo propio, que lo distingue del resto de artistas del lente. Sus registros ostentan diversas capas semánticas, permitiendo distintas lecturas, a partir de la sensibilidad de cada espectador.",
      "Su individual “Imágenes de Carnaval: Centro, Sur y Línea Nordeste” que hoy presentamos en la planta de calle del Centro de la Imagen, conforma un rico conjunto que fotografías realizadas en varias provincias de la geografía dominicana. Esta selección de imágenes representa una mirada sincera y honesta a nuestro carnaval provinciano, en las que capta esa verdadera emoción de participar en esta festividad popular que libera todo tipo de emociones y deseos reprimidos entre los participantes. Es mucho más que disfrazarse de nuestros pintorescos personajes, es vivir la intensidad del momento, y la forma de conservar nuestras tradiciones, en una fiesta que permite aquilatar nuestra identidad y diversidad cultural.",
      "Si bien este año, por motivo de la pandemia, no tendremos carnaval en la forma tradicional y multitudinaria que lo conocemos, tenemos el consuelo de apreciar, a través de este conjunto, de esa mirada del artista, que hurga, escruta y explora más allá de las simples apariencias. Esta espléndida muestra de Farías-Nardi nos trae el aliento fresco del mismo, y nos infunde ánimo para soportar los rigores de estos tiempos en que nos ha tocado vivir.",
      "Carlos Acero Ruiz",
    ],
    image: "/images/event5.webp",
    dates: "Desde 16 feb de 2021",
    entree: getPrice(),
    location: "Calle Arzobispo Meriño, 464",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Centro de la Imagen"],
    artists: ["Pedro Farias-Nardi"],
    artworks: [],
  },
  {
    id: 6,
    title: "Luis Cruz Azaceta: Personal Velocity in the Age of Covid",
    description: [
      "La galería Lyle O. Reitzel Arte Contemporáneo celebra sus 27 años de existencia, presentando una espectacular exposición individual a cargo del artista dominicano Gerard Ellis, titulada “Tierra De Nadie”.",
    ],
    image: "/images/event6.jpg",
    dates: "05 may de 2022 - 30 jun de 2022",
    entree: getPrice(),
    location: "Gustavo Mejia Ricart, Esq. Av. Abraham Lincoln",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Lyle O. Reitzel Gallery"],
    artists: ["Luis Cruz Azaceta"],
    artworks: [],
  },
  {
    id: 7,
    title: "Viviendo En Una Caja",
    description: [
      "23 fotografías donde el autor muestra su perspectiva personal respecto a lo que significó vivir el confinamiento, a raíz de la pandemia COVID-19, en su pequeño departamento ubicado en la ciudad de Nueva York.",
      "Además de las fotografías, la exposición incluye un viaje virtual que permitirá a los visitantes desplazarse, gracias a la tecnología, al hogar del artista en Estados Unidos, el mismo lugar donde fueron recreadas las fotos, y disfrutar de una experiencia inmersiva que plasma las diferentes situaciones de cómo vivimos y nos fuimos adaptando a desafíos que todos experimentamos este año.",
    ],
    image: "/images/event7.webp",
    dates: "15 dic de 2020 - 15 ene de 2021",
    entree: getPrice(),
    location: "Calle Arzobispo Meriño, 464",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Centro de la Imagen"],
    artists: ["Daniel Harel"],
    artworks: [],
  },
  {
    id: 8,
    title: "Festival Internacional de Poesía y Arte Grito de Mujer 2020",
    description: [
      "Cada año, cientos de familias alrededor del mundo son tocadas por la tragedia gracias a los casos de feminicidio. Muchas son las consecuencias y cientos son las víctimas colaterales de cuyo destino pocas veces se habla. El próximo mes de marzo 2020, la cadena mundial del Festival Internacional Grito de Mujer, cumplirá 10 años desde su fundación en 2011. Queremos celebrar este esfuerzo constante entablando una conversación sobre las víctimas más vulnerables del feminicidio desde las artes: los niños y niñas. Para ello, necesitamos aunar nuestros esfuerzos, y contar con el respaldo de instituciones, grupos culturales, poetas y artistas solidarios que, como cada año, se sumen y apoyen nuestra misión social de llevar un mensaje de solidaridad a las víctimas coordinando un evento desde sus ciudades. Para el 2020, el Festival Internacional de Poesía y Arte Grito de Mujer, en su décima emisión, llevará el lema: “Quién grita por ti?”, un grito solidario por los niños y niñas cuyas familias han sido gravemente afectadas por casos de feminicidios. ¡Súmate a la cadena simultanea de eventos Grito de Mujer 2020! a celebrarse del 1ro al 31 de marzo en países de los cinco continentes, con eventos creados por colaboradores voluntarios.",
      "Si deseas formar parte de esta convocatoria que llega gracias al Movimiento Mujeres Poetas Internacional MPI Inc., fundado en la República Dominicana, y coordinar un evento dentro de la cadena Grito de Mujer en tu ciudad*, puedes solicitar las bases de participación contactando al equipo coordinador vía el menú de contacto de la página www.gritodemujer.com y enviar tu propuesta a consideración.",
      "Grito de Mujer es una causa solidaria, que cuenta con el apoyo de cientos de colaboradores altruistas en varias ciudades del mundo, que suman fuerzas y recursos para ayudarnos a llevar nuestro mensaje en favor de quienes verdaderamente lo necesitan. Gracias a ellos, hemos coordinado alrededor de mil eventos en más de 70 países. Conoce quienes somos y lo que hacemos. Sé parte tú también de nuestro grito en favor de quienes se hacen más fuertes, con nuestra voz.",
      "¡Gracias por apoyarnos estos 10 años!",
      "*La aprobación de esta solicitud dependerá de lo relevante de la propuesta y de las ciudades que no estén listadas de antemano como participantes. No aplica para la República Dominicana, sede del festival.",
    ],
    image: "/images/event8.webp",
    dates: "01 mar de 2020 - 31 mar de 2020",
    entree: getPrice(),
    location: "Online",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Mujeres Poetas Internacional MPI Inc."],
    artists: [],
    artworks: [],
  },
  {
    id: 9,
    title: "Figuración Geométrica",
    description: [
      "Artistas: Luis Cruz Azaceta, José Bedia, Gerard Ellis, Gustavo Acosta, Edouard Duval Carriè, Ignacio Iturria, José García Cordero, Gustavo Peña, Tania Marmolejo, Los Bravú, Fernando Varela, Pierre Monestier, Melissa Mejia, Santiago Ydañez",
    ],
    image: "/images/event9.webp",
    dates: "Desde 02 ene de 2020",
    entree: getPrice(),
    location: "Gustavo Mejia Ricart, Esq. Av. Abraham Lincoln",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Lyle O. Reitzel Gallery"],
    artists: [
      "Edouard Duval-Carrié",
      "Fernando Varela",
      "Gerard Ellis",
      "Gustavo Acosta",
      "Gustavo Peña",
      "Ignacio Iturria",
      "José Bedia",
      "José García Cordero",
      "Los Bravú",
      "Luis Cruz Azaceta",
      "Santiago Ydáñez",
      "Tania Marmolejo",
    ],
    artworks: [],
  },
  {
    id: 10,
    title: "Utopia, Espacios y Lenguaje del Arte Caribeño",
    description: [
      "VI Congreso Internacional de Artistas Visuales “Utopías, espacios y lenguajes del arte caribeño contemporáneo”, Homenaje a Tony Capellán.",
      "Artistas El Caribe en Puerto Rico en las artes visuales, APAP",
      "Los artistas del Proyecto el Caribe en Puerto Rico dentro de las artes visuales de la Asociación Puertorriqueña de Artistas Plásticos (APAP), afiliada a la Asociación Internacional de Artes Plásticas en alianza con la UNESCO (AIAP-IAA), fue invitada a participar en el VI Congreso Internacional de Artistas Visuales de la Facultad de Arte de la Universidad Autónoma de Santo Domingo, que este año se presenta con el tema “Utopías, espacios y lenguajes del arte caribeño contemporáneo”, Homenaje a Tony Capellán.",
      "El VI Congreso enmarca en su organización una exposición de artistas del Caribe a inaugurarse del martes, 5 al 25 de noviembre en las sala de exposiciones de la Facultad de Arte de la UASD. El VI Congreso es el miércoles, 6 de noviembre de 8:00 a.m. a 8:00 p.m.",
      "La muestra El Caribe en Puerto Rico dentro de las artes visuales la componen 22 obras de los artistas de la APAP.",
    ],
    image: "/images/event10.webp",
    dates: "05 nov de 2019 - 31 dic de 2019",
    entree: getPrice(),
    location: "Facultad de Arte - Universidad Autónoma de Santo Domingo",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: [
      "Asociación Puertorriqueña de Artistas Plásticos (APAP| AIAP\\UNESCO)",
      "VI Congreso Internacional de Artes Visuales - Facultad de Arte - Universidad Autónoma de Santo Domingo (UASD)",
    ],
    artists: ["Antonio Cortés Rolón", "Tony Capellán"],
    artworks: [],
  },
  {
    id: 11,
    title: "Bitácora",
    description: [
      "El cuerpo es un contexto compuesto por múltiples recorridos. Conocerlo es parecido a explorar a una ciudad. Se recorren mentes, pieles, sabores, sonidos y energías que se vuelven parte de nosotros, de nuestra historia. Cada uno explora un universo entero y se transforma constantemente.",
      "Bitácora es una selección de piezas que presentan el registro de un viaje por diversos cuerpos en la experiencia de cinco mujeres que se narran desde distintos contextos. La auto-exploración, la belleza desaprendida, la sexualidad libre, el tacto y la experimentación con materiales y texturas son algunos de los temas tratados.",
      "Cada pieza que compone la exhibición en su totalidad representa un episodio individual que unidos forman el recorrido de un cuerpo conceptual en una historia completa.",
    ],
    image: "/images/event11.webp",
    dates: "03 ago de 2019 - 29 sep de 2019",
    entree: getPrice(),
    location: "Calle Arzobispo Nouel 158",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["La Mochila Cowork & Office"],
    artists: ["Daniela Urdaneta"],
    artworks: [],
  },
  {
    id: 12,
    title: "Antonio Guadalupe",
    description: [
      "La exposición, que estará compuesta por unos 25 dibujos de diversos formatos forma parte de una colección que el artista ha venido realizando por varios años y que representan la convivencia del ser humano con el ambiente y la fauna global.",
      "En esta presentación, Antonio Guadalupe muestra dibujos de los signos relacionados con la cultura indígena taína, basados en un grafismo caligráfico de belleza sin par, captado con la técnica y estilo del artista.",
      "Dichos dibujos, están realizados en técnica mixta (color y tinta) sobre papelcraft, canson y otros.",
    ],
    image: "/images/event12.webp",
    dates: "Desde 10 jul de 2019",
    entree: getPrice(),
    location: "Padre Billini 202, Ciudad Colonial",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Fundación Quinta Dominica"],
    artists: ["Antonio Guadalupe"],
    artworks: [],
  },
  {
    id: 13,
    title: "Preludio circular",
    description: [
      "En esta exposición, el artista nos presenta 22 obras realizadas en Lienzografías sobre canvas en aluminio en formato circular, mostrando la feminidad de la naturaleza que junto a lo sensual constituyen sus ejes temáticos.",
    ],
    image: "/images/event1.jpg",
    dates: "11 may de 2022 - 11 jul de 2022",
    entree: getPrice(),
    location: "Plaza de la Cultura Juan Pablo Duarte",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Museo de Arte Moderno de Santo Domingo - MAM"],
    artists: [],
    artworks: [
      "/images/event1-1.jpg",
      "/images/event1-2.jpg",
      "/images/event1-3.jpg",
      "/images/event1-4.jpg",
      "/images/event1-5.jpg",
      "/images/event1-6.webp",
      "/images/event1-7.webp",
      "/images/event1-8.webp",
      "/images/event1-9.webp",
    ],
  },
  {
    id: 14,
    title: "Tierra de Nadie",
    description: [
      "La galería Lyle O. Reitzel Arte Contemporáneo celebra sus 27 años de existencia, presentando una espectacular exposición individual a cargo del artista dominicano Gerard Ellis, titulada “Tierra De Nadie”.",
    ],
    image: "/images/event2.jpg",
    dates: "05 may de 2022 - 30 jun de 2022",
    entree: getPrice(),
    location: "Gustavo Mejia Ricart, Esq. Av. Abraham Lincoln",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Lyle O. Reitzel Gallery"],
    artists: ["Gerard Ellis"],
    artworks: [],
  },
  {
    id: 15,
    title: "DIALOGOS ANALOGICOS",
    description: [
      "Esta exposición es una invitación a conocer las inquietudes de un grupo de mujeres que comparten el amor por la fotografía analógica y que buscan comunicar, mediante un discurso visual cargado de verdad y belleza, lo que significa ser mujer en el mundo.",
    ],
    image: "/images/event3.png",
    dates: "04 mar de 2022 - 16 abr de 2022",
    entree: getPrice(),
    location: "Centro Cultural de España",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Centro Cultural de España - CCE Santo Domingo"],
    artists: [""],
    artworks: [],
  },
  {
    id: 16,
    title: "En busca de lo imposible",
    description: ["Seis artistas hiperrealistas en un solo espacio."],
    image: "/images/event4.jpg",
    dates: "Desde 16 feb de 2022",
    entree: getPrice(),
    location: "Galería ASR Contemporáneo",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Galería ASR Contemporáneo"],
    artists: [
      "Domingo Rosario",
      "Francisco Collado",
      "Karina Rodríguez",
      "Pamela Rivera",
      "Ruddy Taveras",
      "Windel Gonzalez",
    ],
    artworks: [],
  },
  {
    id: 17,
    title: "Imágenes de Carnaval: Centro, Sur y Línea Nordeste",
    description: [
      "¿De dónde vienen estas olas?",
      "Pedro Farías-Nardi es una de las personalidades artísticas más reflexivas y definidas en el mundo de la creación fotográfica dominicana. Posee una sólida formación como antropólogo social. De igual forma, una extensa preparación en el quehacer fotográfico en prestigiosas instituciones internacionales. Entre sus principales maestros del lente podemos citar a Susan Meiselas, Antonin Kratochvil, Davild Alan Harvey, Larry Fink y Bob Aldeman para solo mencionar a algunos. Docente universitario, con una vasta cultura, desarrollada en más de tres décadas, lo convierten en un antropólogo visual de primer orden en nuestro país.",
      "Su forma de acercarse a sus retratados, con un prodigioso manejo de un lente fijo y un encuadre muy particular, lo hacen poseedor de un estilo propio, que lo distingue del resto de artistas del lente. Sus registros ostentan diversas capas semánticas, permitiendo distintas lecturas, a partir de la sensibilidad de cada espectador.",
      "Su individual “Imágenes de Carnaval: Centro, Sur y Línea Nordeste” que hoy presentamos en la planta de calle del Centro de la Imagen, conforma un rico conjunto que fotografías realizadas en varias provincias de la geografía dominicana. Esta selección de imágenes representa una mirada sincera y honesta a nuestro carnaval provinciano, en las que capta esa verdadera emoción de participar en esta festividad popular que libera todo tipo de emociones y deseos reprimidos entre los participantes. Es mucho más que disfrazarse de nuestros pintorescos personajes, es vivir la intensidad del momento, y la forma de conservar nuestras tradiciones, en una fiesta que permite aquilatar nuestra identidad y diversidad cultural.",
      "Si bien este año, por motivo de la pandemia, no tendremos carnaval en la forma tradicional y multitudinaria que lo conocemos, tenemos el consuelo de apreciar, a través de este conjunto, de esa mirada del artista, que hurga, escruta y explora más allá de las simples apariencias. Esta espléndida muestra de Farías-Nardi nos trae el aliento fresco del mismo, y nos infunde ánimo para soportar los rigores de estos tiempos en que nos ha tocado vivir.",
      "Carlos Acero Ruiz",
    ],
    image: "/images/event5.webp",
    dates: "Desde 16 feb de 2021",
    entree: getPrice(),
    location: "Calle Arzobispo Meriño, 464",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Centro de la Imagen"],
    artists: ["Pedro Farias-Nardi"],
    artworks: [],
  },
  {
    id: 18,
    title: "Luis Cruz Azaceta: Personal Velocity in the Age of Covid",
    description: [
      "La galería Lyle O. Reitzel Arte Contemporáneo celebra sus 27 años de existencia, presentando una espectacular exposición individual a cargo del artista dominicano Gerard Ellis, titulada “Tierra De Nadie”.",
    ],
    image: "/images/event6.jpg",
    dates: "05 may de 2022 - 30 jun de 2022",
    entree: getPrice(),
    location: "Gustavo Mejia Ricart, Esq. Av. Abraham Lincoln",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Lyle O. Reitzel Gallery"],
    artists: ["Luis Cruz Azaceta"],
    artworks: [],
  },
  {
    id: 19,
    title: "Viviendo En Una Caja",
    description: [
      "23 fotografías donde el autor muestra su perspectiva personal respecto a lo que significó vivir el confinamiento, a raíz de la pandemia COVID-19, en su pequeño departamento ubicado en la ciudad de Nueva York.",
      "Además de las fotografías, la exposición incluye un viaje virtual que permitirá a los visitantes desplazarse, gracias a la tecnología, al hogar del artista en Estados Unidos, el mismo lugar donde fueron recreadas las fotos, y disfrutar de una experiencia inmersiva que plasma las diferentes situaciones de cómo vivimos y nos fuimos adaptando a desafíos que todos experimentamos este año.",
    ],
    image: "/images/event7.webp",
    dates: "15 dic de 2020 - 15 ene de 2021",
    entree: getPrice(),
    location: "Calle Arzobispo Meriño, 464",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Centro de la Imagen"],
    artists: ["Daniel Harel"],
    artworks: [],
  },
  {
    id: 20,
    title: "Festival Internacional de Poesía y Arte Grito de Mujer 2020",
    description: [
      "Cada año, cientos de familias alrededor del mundo son tocadas por la tragedia gracias a los casos de feminicidio. Muchas son las consecuencias y cientos son las víctimas colaterales de cuyo destino pocas veces se habla. El próximo mes de marzo 2020, la cadena mundial del Festival Internacional Grito de Mujer, cumplirá 10 años desde su fundación en 2011. Queremos celebrar este esfuerzo constante entablando una conversación sobre las víctimas más vulnerables del feminicidio desde las artes: los niños y niñas. Para ello, necesitamos aunar nuestros esfuerzos, y contar con el respaldo de instituciones, grupos culturales, poetas y artistas solidarios que, como cada año, se sumen y apoyen nuestra misión social de llevar un mensaje de solidaridad a las víctimas coordinando un evento desde sus ciudades. Para el 2020, el Festival Internacional de Poesía y Arte Grito de Mujer, en su décima emisión, llevará el lema: “Quién grita por ti?”, un grito solidario por los niños y niñas cuyas familias han sido gravemente afectadas por casos de feminicidios. ¡Súmate a la cadena simultanea de eventos Grito de Mujer 2020! a celebrarse del 1ro al 31 de marzo en países de los cinco continentes, con eventos creados por colaboradores voluntarios.",
      "Si deseas formar parte de esta convocatoria que llega gracias al Movimiento Mujeres Poetas Internacional MPI Inc., fundado en la República Dominicana, y coordinar un evento dentro de la cadena Grito de Mujer en tu ciudad*, puedes solicitar las bases de participación contactando al equipo coordinador vía el menú de contacto de la página www.gritodemujer.com y enviar tu propuesta a consideración.",
      "Grito de Mujer es una causa solidaria, que cuenta con el apoyo de cientos de colaboradores altruistas en varias ciudades del mundo, que suman fuerzas y recursos para ayudarnos a llevar nuestro mensaje en favor de quienes verdaderamente lo necesitan. Gracias a ellos, hemos coordinado alrededor de mil eventos en más de 70 países. Conoce quienes somos y lo que hacemos. Sé parte tú también de nuestro grito en favor de quienes se hacen más fuertes, con nuestra voz.",
      "¡Gracias por apoyarnos estos 10 años!",
      "*La aprobación de esta solicitud dependerá de lo relevante de la propuesta y de las ciudades que no estén listadas de antemano como participantes. No aplica para la República Dominicana, sede del festival.",
    ],
    image: "/images/event8.webp",
    dates: "01 mar de 2020 - 31 mar de 2020",
    entree: getPrice(),
    location: "Online",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Mujeres Poetas Internacional MPI Inc."],
    artists: [],
    artworks: [],
  },
  {
    id: 21,
    title: "Figuración Geométrica",
    description: [
      "Artistas: Luis Cruz Azaceta, José Bedia, Gerard Ellis, Gustavo Acosta, Edouard Duval Carriè, Ignacio Iturria, José García Cordero, Gustavo Peña, Tania Marmolejo, Los Bravú, Fernando Varela, Pierre Monestier, Melissa Mejia, Santiago Ydañez",
    ],
    image: "/images/event9.webp",
    dates: "Desde 02 ene de 2020",
    entree: getPrice(),
    location: "Gustavo Mejia Ricart, Esq. Av. Abraham Lincoln",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Lyle O. Reitzel Gallery"],
    artists: [
      "Edouard Duval-Carrié",
      "Fernando Varela",
      "Gerard Ellis",
      "Gustavo Acosta",
      "Gustavo Peña",
      "Ignacio Iturria",
      "José Bedia",
      "José García Cordero",
      "Los Bravú",
      "Luis Cruz Azaceta",
      "Santiago Ydáñez",
      "Tania Marmolejo",
    ],
    artworks: [],
  },
  {
    id: 22,
    title: "Utopia, Espacios y Lenguaje del Arte Caribeño",
    description: [
      "VI Congreso Internacional de Artistas Visuales “Utopías, espacios y lenguajes del arte caribeño contemporáneo”, Homenaje a Tony Capellán.",
      "Artistas El Caribe en Puerto Rico en las artes visuales, APAP",
      "Los artistas del Proyecto el Caribe en Puerto Rico dentro de las artes visuales de la Asociación Puertorriqueña de Artistas Plásticos (APAP), afiliada a la Asociación Internacional de Artes Plásticas en alianza con la UNESCO (AIAP-IAA), fue invitada a participar en el VI Congreso Internacional de Artistas Visuales de la Facultad de Arte de la Universidad Autónoma de Santo Domingo, que este año se presenta con el tema “Utopías, espacios y lenguajes del arte caribeño contemporáneo”, Homenaje a Tony Capellán.",
      "El VI Congreso enmarca en su organización una exposición de artistas del Caribe a inaugurarse del martes, 5 al 25 de noviembre en las sala de exposiciones de la Facultad de Arte de la UASD. El VI Congreso es el miércoles, 6 de noviembre de 8:00 a.m. a 8:00 p.m.",
      "La muestra El Caribe en Puerto Rico dentro de las artes visuales la componen 22 obras de los artistas de la APAP.",
    ],
    image: "/images/event10.webp",
    dates: "05 nov de 2019 - 31 dic de 2019",
    entree: getPrice(),
    location: "Facultad de Arte - Universidad Autónoma de Santo Domingo",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: [
      "Asociación Puertorriqueña de Artistas Plásticos (APAP| AIAP\\UNESCO)",
      "VI Congreso Internacional de Artes Visuales - Facultad de Arte - Universidad Autónoma de Santo Domingo (UASD)",
    ],
    artists: ["Antonio Cortés Rolón", "Tony Capellán"],
    artworks: [],
  },
  {
    id: 23,
    title: "Bitácora",
    description: [
      "El cuerpo es un contexto compuesto por múltiples recorridos. Conocerlo es parecido a explorar a una ciudad. Se recorren mentes, pieles, sabores, sonidos y energías que se vuelven parte de nosotros, de nuestra historia. Cada uno explora un universo entero y se transforma constantemente.",
      "Bitácora es una selección de piezas que presentan el registro de un viaje por diversos cuerpos en la experiencia de cinco mujeres que se narran desde distintos contextos. La auto-exploración, la belleza desaprendida, la sexualidad libre, el tacto y la experimentación con materiales y texturas son algunos de los temas tratados.",
      "Cada pieza que compone la exhibición en su totalidad representa un episodio individual que unidos forman el recorrido de un cuerpo conceptual en una historia completa.",
    ],
    image: "/images/event11.webp",
    dates: "03 ago de 2019 - 29 sep de 2019",
    entree: getPrice(),
    location: "Calle Arzobispo Nouel 158",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["La Mochila Cowork & Office"],
    artists: ["Daniela Urdaneta"],
    artworks: [],
  },
  {
    id: 24,
    title: "Antonio Guadalupe",
    description: [
      "La exposición, que estará compuesta por unos 25 dibujos de diversos formatos forma parte de una colección que el artista ha venido realizando por varios años y que representan la convivencia del ser humano con el ambiente y la fauna global.",
      "En esta presentación, Antonio Guadalupe muestra dibujos de los signos relacionados con la cultura indígena taína, basados en un grafismo caligráfico de belleza sin par, captado con la técnica y estilo del artista.",
      "Dichos dibujos, están realizados en técnica mixta (color y tinta) sobre papelcraft, canson y otros.",
    ],
    image: "/images/event12.webp",
    dates: "Desde 10 jul de 2019",
    entree: getPrice(),
    location: "Padre Billini 202, Ciudad Colonial",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Fundación Quinta Dominica"],
    artists: ["Antonio Guadalupe"],
    artworks: [],
  },
  {
    id: 25,
    title: "Antonio Guadalupe",
    description: [
      "La exposición, que estará compuesta por unos 25 dibujos de diversos formatos forma parte de una colección que el artista ha venido realizando por varios años y que representan la convivencia del ser humano con el ambiente y la fauna global.",
      "En esta presentación, Antonio Guadalupe muestra dibujos de los signos relacionados con la cultura indígena taína, basados en un grafismo caligráfico de belleza sin par, captado con la técnica y estilo del artista.",
      "Dichos dibujos, están realizados en técnica mixta (color y tinta) sobre papelcraft, canson y otros.",
    ],
    image: "/images/event12.webp",
    dates: "Desde 10 jul de 2019",
    entree: getPrice(),
    location: "Padre Billini 202, Ciudad Colonial",
    people: `${parseInt(getRandomNumber(2, 100))}k`,
    organizers: ["Fundación Quinta Dominica"],
    artists: ["Antonio Guadalupe"],
    artworks: [],
  },
]);
